// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2450.ShawMedallion.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2450.ShawMedallion.Robot;
import org.usfirst.frc2450.ShawMedallion.subsystems.LimelightSubsystem;

/**
 *
 */
public class TargetSeek extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public TargetSeek() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.limelightSubsystem);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    double Kp = 0.03d;
    double min_command = 0.05d;
    double i = 0;
    
    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        i += 0.005;
        double heading_error = -LimelightSubsystem.getTx();
        double steering_adjust = 0.0d;
        if (LimelightSubsystem.getTx() > 1.0)
        {
                steering_adjust = -Kp*heading_error - min_command;
        }
        else if (LimelightSubsystem.getTx() < -1.0)
        {
                steering_adjust = -Kp*heading_error + min_command;
        }
      
        Robot.driveDrainSubsytem.getRobotDrive().driveCartesian(0, 0, steering_adjust+i);

    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return(LimelightSubsystem.getTx() > -1 && LimelightSubsystem.getTx() < 1);
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.driveDrainSubsytem.getRobotDrive().driveCartesian(0, 0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
